import { existsSync, realpathSync } from "node:fs";
import {
  lstat,
  mkdir,
  readdir,
  readFile,
  readlink,
  writeFile,
  symlink,
} from "node:fs/promises";
import { basename, dirname, join, resolve } from "node:path";
import { fileURLToPath, pathToFileURL } from "node:url";

import { afterEach, describe, expect, it, vi } from "vitest";

import { doctorAll, doctorRuntime, recordHostHeartbeat } from "../src/doctor.js";
import {
  INSTALL_RUNTIMES,
  installRuntime,
  isRuntimeConfigured,
  uninstallRuntime,
  type InstallRuntime,
  type InstallScope,
} from "../src/install/index.js";
import { runCli } from "../src/cli.js";
import { makeTempProject, withStateDir } from "./helpers.js";

const SOURCE_ROOT = resolve(dirname(fileURLToPath(import.meta.url)), "..", "src");
const LOADER_MARKER = "// Generated by TaskFence. Do not edit.";
const originalOpenCodeConfigDir = process.env.OPENCODE_CONFIG_DIR;

function adapterPath(runtime: InstallRuntime): string {
  const filename = runtime === "claude"
    ? "claude-code.js"
    : runtime === "codex"
      ? "codex-cli.js"
      : `${runtime}.js`;
  return join(SOURCE_ROOT, "adapters", filename);
}

function canonicalPath(path: string): string {
  let existing = resolve(path);
  const missingSegments: string[] = [];
  while (!existsSync(existing)) {
    missingSegments.push(basename(existing));
    existing = dirname(existing);
  }
  return join(realpathSync(existing), ...missingSegments.reverse());
}

function expectedPath(
  runtime: InstallRuntime,
  scope: InstallScope,
  root: string,
  home: string,
): string {
  const base = canonicalPath(scope === "user" ? home : root);
  switch (runtime) {
    case "claude":
      return join(base, ".claude", "settings.json");
    case "codex":
      return join(base, ".codex", "hooks.json");
    case "opencode":
      return scope === "user"
        ? join(base, ".config", "opencode", "plugins", "taskfence.ts")
        : join(base, ".opencode", "plugins", "taskfence.ts");
    case "omp":
      return scope === "user"
        ? join(base, ".omp", "agent", "extensions", "taskfence.js")
        : join(base, ".omp", "extensions", "taskfence.js");
    case "pi":
      return scope === "user"
        ? join(base, ".pi", "agent", "extensions", "taskfence.js")
        : join(base, ".pi", "extensions", "taskfence.js");
  }
}

async function readJson(path: string): Promise<Record<string, unknown>> {
  return JSON.parse(await readFile(path, "utf8")) as Record<string, unknown>;
}

afterEach(() => {
  if (originalOpenCodeConfigDir === undefined) {
    delete process.env.OPENCODE_CONFIG_DIR;
  } else {
    process.env.OPENCODE_CONFIG_DIR = originalOpenCodeConfigDir;
  }
});

describe.each(["user", "project"] as const)("%s-scope installation", (scope) => {
  it.each(INSTALL_RUNTIMES)("installs, inspects, and uninstalls %s idempotently at the exact path", async (runtime) => {
    const project = await makeTempProject(`taskfence-installer-${scope}-${runtime}-`);
    const home = join(dirname(project.root), "home");
    const nodePath = join(dirname(project.root), "bin", "node");
    const cliPath = join(dirname(project.root), "dist", "cli.js");
    const options = { scope, root: project.root, home, nodePath, cliPath } as const;
    const path = expectedPath(runtime, scope, project.root, home);

    try {
      const installed = await installRuntime(runtime, options);
      expect(installed).toEqual({ runtime, scope, path, action: "installed" });

      if (runtime === "claude" || runtime === "codex") {
        const config = await readJson(path);
        const expectedHandler = runtime === "claude"
          ? {
              type: "command",
              command: nodePath,
              args: [cliPath, "hook", "claude"],
              statusMessage: "TaskFence policy check",
            }
          : {
              type: "command",
              command: `'${nodePath}' '${cliPath}' hook codex`,
              statusMessage: "TaskFence policy check",
            };
        expect(config).toEqual({
          hooks: {
            PreToolUse: [{ matcher: "*", hooks: [expectedHandler] }],
            PostToolUse: [{ matcher: "*", hooks: [expectedHandler] }],
          },
        });
      } else if (runtime === "opencode") {
        expect(await readFile(path, "utf8")).toBe(
          `${LOADER_MARKER}\nimport TaskFencePlugin from ${JSON.stringify(pathToFileURL(adapterPath(runtime)).href)};\n\nexport default TaskFencePlugin;\n`,
        );
      } else {
        expect((await lstat(path)).isSymbolicLink()).toBe(true);
        expect(resolve(dirname(path), await readlink(path))).toBe(adapterPath(runtime));
      }

      await expect(isRuntimeConfigured(runtime, options)).resolves.toEqual({
        configured: true,
        path,
        detail: runtime === "claude" || runtime === "codex"
          ? "PreToolUse and PostToolUse hooks configured"
          : runtime === "opencode"
            ? "TaskFence loader configured"
            : "TaskFence extension symlink configured",
      });
      await expect(installRuntime(runtime, options)).resolves.toEqual({
        runtime,
        scope,
        path,
        action: "unchanged",
      });
      const removed = await uninstallRuntime(runtime, options);
      expect(removed).toEqual(runtime === "claude" || runtime === "codex"
        ? {
            runtime,
            scope,
            path,
            action: "removed",
            backupPath: expect.stringContaining(`${path}.taskfence-backup-`),
          }
        : { runtime, scope, path, action: "removed" });
      expect((await isRuntimeConfigured(runtime, options)).configured).toBe(false);
      await expect(uninstallRuntime(runtime, options)).resolves.toEqual({
        runtime,
        scope,
        path,
        action: "not-installed",
      });
    } finally {
      await project.cleanup();
    }
  });
});

describe("all-runtime installation", () => {
  it.each(["user", "project"] as const)(
    "installs and uninstalls exactly all five runtimes through the CLI in %s scope",
    async (scope) => {
      const project = await makeTempProject(`taskfence-installer-all-${scope}-`);
      const home = join(dirname(project.root), "home");
      const previousHome = process.env.HOME;
      const stdout: string[] = [];
      const stderr: string[] = [];
      process.env.HOME = home;
      delete process.env.OPENCODE_CONFIG_DIR;
      vi.spyOn(process.stdout, "write").mockImplementation((chunk) => {
        stdout.push(String(chunk));
        return true;
      });
      vi.spyOn(process.stderr, "write").mockImplementation((chunk) => {
        stderr.push(String(chunk));
        return true;
      });

      try {
        await expect(runCli([
          "install",
          "all",
          "--scope",
          scope,
          "--root",
          project.root,
          "--json",
        ])).resolves.toBe(0);
        expect(stderr).toEqual([]);
        const reports = JSON.parse(stdout.join("")) as Array<Record<string, unknown>>;
        expect(reports.map((report) => report.runtime)).toEqual(INSTALL_RUNTIMES);
        expect(reports.map((report) => report.path)).toEqual(
          INSTALL_RUNTIMES.map((runtime) => expectedPath(runtime, scope, project.root, home)),
        );
        expect(reports.every((report) => report.action === "installed")).toBe(true);

        stdout.length = 0;
        await expect(runCli([
          "uninstall",
          "all",
          "--scope",
          scope,
          "--root",
          project.root,
          "--json",
        ])).resolves.toBe(0);
        const removals = JSON.parse(stdout.join("")) as Array<Record<string, unknown>>;
        expect(removals.map((report) => report.runtime)).toEqual(INSTALL_RUNTIMES);
        expect(removals.every((report) => report.action === "removed")).toBe(true);
      } finally {
        if (previousHome === undefined) delete process.env.HOME;
        else process.env.HOME = previousHome;
        await project.cleanup();
      }
    },
  );
});

describe("configuration preservation and ownership", () => {
  it.each(["claude", "codex"] as const)("preserves unrelated %s config and removes only owned handlers", async (runtime) => {
    const project = await makeTempProject(`taskfence-installer-preserve-${runtime}-`);
    const home = join(dirname(project.root), "home");
    const path = expectedPath(runtime, "user", project.root, home);
    const unrelatedHandler = {
      type: "command",
      command: "/usr/local/bin/other-hook",
      statusMessage: "Other policy",
    };
    const original = {
      theme: "dark",
      hooks: {
        PreToolUse: [{ matcher: "Write", hooks: [unrelatedHandler], custom: true }],
        PostToolUse: [{ matcher: "*", hooks: [unrelatedHandler] }],
        Notification: [{ matcher: "*", hooks: [unrelatedHandler] }],
      },
      nested: { untouched: [1, 2, 3] },
    };
    await mkdir(dirname(path), { recursive: true });
    await writeFile(path, `${JSON.stringify(original, null, 2)}\n`);

    try {
      const installed = await installRuntime(runtime, {
        scope: "user",
        root: project.root,
        home,
        nodePath: "/taskfence/node",
        cliPath: "/taskfence/cli.js",
      });
      expect(installed.action).toBe("updated");
      expect(installed.backupPath).toBeDefined();
      expect(await readFile(installed.backupPath!, "utf8")).toBe(`${JSON.stringify(original, null, 2)}\n`);

      const configured = await readJson(path);
      expect(configured.theme).toBe("dark");
      expect(configured.nested).toEqual(original.nested);
      expect((configured.hooks as Record<string, unknown>).Notification).toEqual(original.hooks.Notification);

      await expect(uninstallRuntime(runtime, {
        scope: "user",
        root: project.root,
        home,
        nodePath: "/taskfence/node",
        cliPath: "/taskfence/cli.js",
      })).resolves.toMatchObject({ action: "removed", path });
      expect(await readJson(path)).toEqual(original);
    } finally {
      await project.cleanup();
    }
  });

  it.each(["claude", "codex"] as const)(
    "requires the complete %s handler and matcher identity before claiming ownership",
    async (runtime) => {
      const project = await makeTempProject(`taskfence-installer-ownership-collisions-${runtime}-`);
      const home = join(dirname(project.root), "home");
      const path = expectedPath(runtime, "user", project.root, home);
      const options = {
        scope: "user",
        root: project.root,
        home,
        nodePath: "/taskfence/node",
        cliPath: "/taskfence/cli.js",
      } as const;
      const exactHandler = runtime === "claude"
        ? {
            type: "command",
            command: options.nodePath,
            args: [options.cliPath, "hook", "claude"],
            statusMessage: "TaskFence policy check",
          }
        : {
            type: "command",
            command: "'/taskfence/node' '/taskfence/cli.js' hook codex",
            statusMessage: "TaskFence policy check",
          };
      const sameStatusDifferentCommand = {
        ...exactHandler,
        command: "/usr/local/bin/unrelated-hook",
      };
      const sameCommandDifferentArgs = {
        ...exactHandler,
        args: ["/usr/local/lib/unrelated-hook.js"],
      };
      const collisionGroups = [
        {
          matcher: "*",
          hooks: [sameStatusDifferentCommand, sameCommandDifferentArgs],
        },
        {
          matcher: "Write",
          hooks: [exactHandler],
        },
      ];
      const original = {
        hooks: {
          PreToolUse: [
            { matcher: "*", hooks: [exactHandler] },
            ...collisionGroups,
          ],
          PostToolUse: [{ matcher: "*", hooks: [exactHandler] }],
        },
      };
      await mkdir(dirname(path), { recursive: true });
      await writeFile(path, `${JSON.stringify(original, null, 2)}\n`);

      try {
        await expect(installRuntime(runtime, options)).resolves.toMatchObject({
          action: "updated",
          path,
        });
        const configured = await readJson(path);
        expect(configured).toEqual({
          hooks: {
            PreToolUse: [
              ...collisionGroups,
              { matcher: "*", hooks: [exactHandler] },
            ],
            PostToolUse: [{ matcher: "*", hooks: [exactHandler] }],
          },
        });
        await expect(isRuntimeConfigured(runtime, options)).resolves.toMatchObject({
          configured: true,
        });

        await expect(uninstallRuntime(runtime, options)).resolves.toMatchObject({
          action: "removed",
          path,
        });
        expect(await readJson(path)).toEqual({
          hooks: {
            PreToolUse: collisionGroups,
          },
        });
        await expect(isRuntimeConfigured(runtime, options)).resolves.toMatchObject({
          configured: false,
        });
      } finally {
        await project.cleanup();
      }
    },
  );

  it("refuses to uninstall unrelated OpenCode and extension entries without deleting them", async () => {
    const project = await makeTempProject("taskfence-installer-foreign-");
    const openCodePath = expectedPath("opencode", "project", project.root, "unused");
    const ompPath = expectedPath("omp", "project", project.root, "unused");
    const foreignTarget = join(dirname(project.root), "foreign-extension.js");
    await mkdir(dirname(openCodePath), { recursive: true });
    await mkdir(dirname(ompPath), { recursive: true });
    await writeFile(openCodePath, "export default function unrelated() {}\n");
    await writeFile(foreignTarget, "export default () => {};\n");
    await symlink(foreignTarget, ompPath);

    try {
      await expect(uninstallRuntime("opencode", { scope: "project", root: project.root }))
        .rejects.toThrow("Refusing to remove unrelated OpenCode plugin");
      expect(await readFile(openCodePath, "utf8")).toBe("export default function unrelated() {}\n");

      await expect(uninstallRuntime("omp", { scope: "project", root: project.root }))
        .rejects.toThrow("Refusing to remove symlink not owned");
      expect(resolve(dirname(ompPath), await readlink(ompPath))).toBe(foreignTarget);
    } finally {
      await project.cleanup();
    }
  });
});

describe("fail-closed installer validation", () => {
  it("does not overwrite malformed JSON or an invalid hooks shape", async () => {
    const project = await makeTempProject("taskfence-installer-invalid-json-");
    const claudePath = expectedPath("claude", "project", project.root, "unused");
    await mkdir(dirname(claudePath), { recursive: true });

    try {
      await writeFile(claudePath, "{not-json\n");
      await expect(installRuntime("claude", { scope: "project", root: project.root }))
        .rejects.toThrow("invalid JSON");
      expect(await readFile(claudePath, "utf8")).toBe("{not-json\n");

      const invalidShape = `${JSON.stringify({ hooks: [] }, null, 2)}\n`;
      await writeFile(claudePath, invalidShape);
      await expect(installRuntime("claude", { scope: "project", root: project.root }))
        .rejects.toThrow("hooks must be a JSON object");
      expect(await readFile(claudePath, "utf8")).toBe(invalidShape);
    } finally {
      await project.cleanup();
    }
  });

  it("rejects Codex inline hooks without creating a competing hooks file", async () => {
    const project = await makeTempProject("taskfence-installer-codex-inline-");
    const configPath = join(project.root, ".codex", "config.toml");
    const hooksPath = expectedPath("codex", "project", project.root, "unused");
    await mkdir(dirname(configPath), { recursive: true });
    await writeFile(configPath, "[[hooks]]\ncommand = 'other'\n");

    try {
      await expect(installRuntime("codex", { scope: "project", root: project.root }))
        .rejects.toThrow("already defines inline hooks");
      await expect(lstat(hooksPath)).rejects.toMatchObject({ code: "ENOENT" });
    } finally {
      await project.cleanup();
    }
  });

  it("rejects invalid custom OpenCode paths and foreign loader path types", async () => {
    const project = await makeTempProject("taskfence-installer-opencode-path-");
    const loaderPath = expectedPath("opencode", "project", project.root, "unused");

    try {
      process.env.OPENCODE_CONFIG_DIR = "relative/config";
      await expect(installRuntime("opencode", {
        scope: "user",
        root: project.root,
        home: dirname(project.root),
      })).rejects.toThrow("OPENCODE_CONFIG_DIR must contain a non-empty absolute path");

      await mkdir(loaderPath, { recursive: true });
      await expect(installRuntime("opencode", { scope: "project", root: project.root }))
        .rejects.toThrow("path is not a regular file");
      expect((await lstat(loaderPath)).isDirectory()).toBe(true);
    } finally {
      await project.cleanup();
    }
  });

  it("rejects NUL-containing option paths before writing configuration", async () => {
    const project = await makeTempProject("taskfence-installer-nul-");
    try {
      await expect(installRuntime("claude", {
        scope: "project",
        root: `${project.root}\0escape`,
      })).rejects.toThrow();
      await expect(lstat(join(project.root, ".claude"))).rejects.toMatchObject({ code: "ENOENT" });
    } finally {
      await project.cleanup();
    }
  });

  it.each(INSTALL_RUNTIMES)(
    "rejects symbolic-link destination ancestors for %s during install, inspect, and uninstall",
    async (runtime) => {
      const project = await makeTempProject(`taskfence-installer-symlink-ancestor-${runtime}-`);
      const ancestorName = runtime === "claude"
        ? ".claude"
        : runtime === "codex"
          ? ".codex"
          : runtime === "opencode"
            ? ".opencode"
            : runtime === "omp"
              ? ".omp"
              : ".pi";
      const outside = join(dirname(project.root), `outside-${runtime}`);
      await mkdir(outside, { recursive: true });
      await symlink(outside, join(project.root, ancestorName));

      try {
        const options = { scope: "project", root: project.root } as const;
        await expect(installRuntime(runtime, options)).rejects.toThrow("ancestor is a symbolic link");
        await expect(isRuntimeConfigured(runtime, options)).resolves.toMatchObject({
          configured: false,
          detail: expect.stringContaining("ancestor is a symbolic link"),
        });
        await expect(uninstallRuntime(runtime, options)).rejects.toThrow("ancestor is a symbolic link");
        expect(await readdir(outside)).toEqual([]);
      } finally {
        await project.cleanup();
      }
    },
  );

  it.each(INSTALL_RUNTIMES)("rejects non-directory destination ancestors for %s", async (runtime) => {
    const project = await makeTempProject(`taskfence-installer-file-ancestor-${runtime}-`);
    const ancestorName = runtime === "claude"
      ? ".claude"
      : runtime === "codex"
        ? ".codex"
        : runtime === "opencode"
          ? ".opencode"
          : runtime === "omp"
            ? ".omp"
            : ".pi";
    await writeFile(join(project.root, ancestorName), "not a directory\n");

    try {
      await expect(installRuntime(runtime, { scope: "project", root: project.root }))
        .rejects.toThrow("ancestor is not a directory");
    } finally {
      await project.cleanup();
    }
  });

  it("canonicalizes a selected scope root before deriving destinations", async () => {
    const project = await makeTempProject("taskfence-installer-canonical-root-");
    const alias = join(dirname(project.root), "project-alias");
    await symlink(project.root, alias);

    try {
      const installed = await installRuntime("claude", { scope: "project", root: alias });
      expect(installed.path).toBe(expectedPath("claude", "project", project.root, "unused"));
      await expect(uninstallRuntime("claude", { scope: "project", root: alias }))
        .resolves.toMatchObject({ action: "removed", path: installed.path });
    } finally {
      await project.cleanup();
    }
  });

  it("rejects a user OpenCode config directory outside the canonical home root", async () => {
    const project = await makeTempProject("taskfence-installer-opencode-escape-");
    const home = join(dirname(project.root), "home");
    const outside = join(dirname(project.root), "outside-opencode");
    await mkdir(outside, { recursive: true });
    process.env.OPENCODE_CONFIG_DIR = outside;

    try {
      await expect(installRuntime("opencode", {
        scope: "user",
        root: project.root,
        home,
      })).rejects.toThrow("outside canonical user scope root");
      await expect(isRuntimeConfigured("opencode", {
        scope: "user",
        root: project.root,
        home,
      })).resolves.toMatchObject({
        configured: false,
        detail: expect.stringContaining("outside canonical user scope root"),
      });
      await expect(uninstallRuntime("opencode", {
        scope: "user",
        root: project.root,
        home,
      })).rejects.toThrow("outside canonical user scope root");
      expect(await readdir(outside)).toEqual([]);
    } finally {
      await project.cleanup();
    }
  });
});

describe("OpenCode configuration directory", () => {
  it("uses an absolute OPENCODE_CONFIG_DIR only for user scope", async () => {
    const project = await makeTempProject("taskfence-installer-opencode-custom-");
    const home = join(dirname(project.root), "home");
    const customConfig = join(home, "custom-opencode");
    process.env.OPENCODE_CONFIG_DIR = customConfig;

    try {
      const user = await installRuntime("opencode", {
        scope: "user",
        root: project.root,
        home,
      });
      expect(user.path).toBe(join(canonicalPath(customConfig), "plugins", "taskfence.ts"));
      expect((await isRuntimeConfigured("opencode", {
        scope: "user",
        root: project.root,
        home,
      })).configured).toBe(true);

      const projectInstall = await installRuntime("opencode", {
        scope: "project",
        root: project.root,
      });
      expect(projectInstall.path).toBe(expectedPath("opencode", "project", project.root, home));
    } finally {
      await project.cleanup();
    }
  });
});

describe("configuration inspection and doctor reporting", () => {
  it("reports incomplete or altered entries as unconfigured with a truthful detail", async () => {
    const project = await makeTempProject("taskfence-installer-inspect-");
    const claudePath = expectedPath("claude", "project", project.root, "unused");
    const loaderPath = expectedPath("opencode", "project", project.root, "unused");
    await mkdir(dirname(claudePath), { recursive: true });
    await mkdir(dirname(loaderPath), { recursive: true });
    await writeFile(claudePath, JSON.stringify({
      hooks: {
        PreToolUse: [{ matcher: "*", hooks: [{ type: "command", command: process.execPath }] }],
      },
    }));
    await writeFile(loaderPath, `${LOADER_MARKER}\nexport default null;\n`);

    try {
      await expect(isRuntimeConfigured("claude", {
        scope: "project",
        root: project.root,
      })).resolves.toMatchObject({
        configured: false,
        path: claudePath,
        detail: "TaskFence PreToolUse hook not found",
      });
      await expect(isRuntimeConfigured("opencode", {
        scope: "project",
        root: project.root,
      })).resolves.toEqual({
        configured: false,
        path: loaderPath,
        detail: "Loader differs from this TaskFence install",
      });
    } finally {
      await project.cleanup();
    }
  });

  it("distinguishes configuration, local artifacts, and unbound adapter-loading observations", async () => {
    const project = await makeTempProject("taskfence-installer-doctor-");

    try {
      await withStateDir(project.stateDir, async () => {
        await installRuntime("omp", { scope: "project", root: project.root });
        const missingCli = join(dirname(project.root), "missing-cli.js");
        const first = await doctorRuntime("omp", {
          scope: "project",
          root: project.root,
          cliPath: missingCli,
          nodePath: process.execPath,
          now: new Date("2026-01-01T00:00:00.000Z"),
        });
        expect(first.configured).toBe(true);
        expect(first.configurationPath.endsWith(join(".omp", "extensions", "taskfence.js"))).toBe(true);
        expect(first.binarySelfTest).toEqual({
          passed: false,
          detail: expect.stringContaining("missing-cli.js"),
        });
        expect(first.hostHeartbeat).toMatchObject({
          status: "missing",
          loadingObserved: false,
          verified: false,
          detail: "No adapter-loading heartbeat observed; configuration and local artifacts do not prove host loading or enforcement",
        });

        await recordHostHeartbeat("omp");
        const recent = await doctorRuntime("omp", {
          scope: "project",
          root: project.root,
          cliPath: missingCli,
          nodePath: process.execPath,
          now: new Date(),
        });
        expect(recent.configured).toBe(true);
        expect(recent.binarySelfTest.passed).toBe(false);
        expect(recent.hostHeartbeat).toMatchObject({
          status: "recent",
          loadingObserved: true,
          verified: false,
          detail: expect.stringMatching(
            /not bound to this project, host process, or session.*does not verify enforcement/iu,
          ),
        });
        const observedAt = recent.hostHeartbeat.observedAt;
        expect(observedAt).toBeTypeOf("string");
        const stale = await doctorRuntime("omp", {
          scope: "project",
          root: project.root,
          cliPath: missingCli,
          nodePath: process.execPath,
          heartbeatMaxAgeMs: 0,
          now: new Date(Date.parse(observedAt!) + 1),
        });
        expect(stale.hostHeartbeat).toMatchObject({
          status: "stale",
          loadingObserved: true,
          verified: false,
          detail: expect.stringMatching(/stale adapter-loading observation.*does not prove/iu),
        });
        const localArtifacts = await doctorRuntime("omp", {
          scope: "project",
          root: project.root,
          nodePath: process.execPath,
          cliPath: join(SOURCE_ROOT, "cli.ts"),
        });
        expect(localArtifacts.binarySelfTest).toEqual({
          passed: false,
          detail: expect.stringContaining(join("src", "adapters", "omp.js")),
        });

        const all = await doctorAll({
          scope: "project",
          root: project.root,
          cliPath: missingCli,
          nodePath: process.execPath,
        });
        expect(all.map((report) => report.runtime)).toEqual(INSTALL_RUNTIMES);
        expect(all.filter((report) => report.configured).map((report) => report.runtime)).toEqual(["omp"]);
        expect(all.every((report) => report.binarySelfTest.passed === false)).toBe(true);
        expect(all.every((report) => report.hostHeartbeat.verified === false)).toBe(true);
        expect(all.find((report) => report.runtime === "omp")?.hostHeartbeat.loadingObserved).toBe(true);
        expect(all.filter((report) => report.runtime !== "omp").every(
          (report) => !report.hostHeartbeat.loadingObserved,
        )).toBe(true);
      });
    } finally {
      await project.cleanup();
    }
  });
});
