import { constants as fsConstants } from "node:fs";
import {
  copyFile,
  lstat,
  mkdir,
  open,
  readFile,
  readlink,
  realpath,
  rename,
  rm,
  symlink,
  writeFile,
} from "node:fs/promises";
import type { FileHandle } from "node:fs/promises";
import { homedir } from "node:os";
import { basename, dirname, isAbsolute, join, relative, resolve, sep } from "node:path";
import { fileURLToPath, pathToFileURL } from "node:url";

import { isJsonObject } from "./json.js";
import type { JsonObject } from "./json.js";

export const INSTALL_RUNTIMES = [
  "claude",
  "codex",
  "opencode",
  "omp",
  "pi",
] as const;

export type InstallRuntime = (typeof INSTALL_RUNTIMES)[number];
export type InstallScope = "user" | "project";

export interface InstallOptions {
  scope?: InstallScope;
  root?: string;
  home?: string;
  nodePath?: string;
  cliPath?: string;
}

export interface InstallReport {
  runtime: InstallRuntime;
  scope: InstallScope;
  path: string;
  action: "installed" | "updated" | "unchanged" | "removed" | "not-installed";
  backupPath?: string;
}

interface ResolvedInstallOptions {
  scope: InstallScope;
  root: string;
  home: string;
  scopeRoot: string;
  scopeInputRoot: string;
  nodePath: string;
  cliPath: string;
}

const LOADER_MARKER = "// Generated by TaskFence. Do not edit.";
const HOOK_STATUS = "TaskFence policy check";
const MODULE_DIRECTORY = dirname(fileURLToPath(import.meta.url));
const DISTRIBUTION_DIRECTORY = basename(MODULE_DIRECTORY) === "install"
  ? dirname(MODULE_DIRECTORY)
  : MODULE_DIRECTORY;

export function isInstallRuntime(value: string): value is InstallRuntime {
  return (INSTALL_RUNTIMES as readonly string[]).includes(value);
}

function isMissingPathError(error: unknown): boolean {
  return typeof error === "object" && error !== null &&
    "code" in error && error.code === "ENOENT";
}

async function canonicalizeScopeRoot(path: string): Promise<string> {
  if (path.includes("\0")) {
    throw new Error("Install scope root cannot contain NUL bytes");
  }

  const absolute = resolve(path);
  const missingSegments: string[] = [];
  let existing = absolute;
  while (true) {
    try {
      const metadata = await lstat(existing);
      if (!metadata.isDirectory() && !metadata.isSymbolicLink()) {
        throw new Error(`Install scope root is not a directory: ${absolute}`);
      }
      const canonicalExisting = await realpath(existing);
      const canonicalMetadata = await lstat(canonicalExisting);
      if (!canonicalMetadata.isDirectory()) {
        throw new Error(`Install scope root is not a directory: ${absolute}`);
      }
      return join(canonicalExisting, ...missingSegments.reverse());
    } catch (error) {
      if (!isMissingPathError(error)) throw error;
      const parent = dirname(existing);
      if (parent === existing) throw error;
      missingSegments.push(basename(existing));
      existing = parent;
    }
  }
}

function assertConfined(path: string, options: ResolvedInstallOptions): void {
  const normalized = resolve(path);
  const fromRoot = relative(options.scopeRoot, normalized);
  if (fromRoot === "" || (!fromRoot.startsWith(`..${sep}`) && fromRoot !== ".." && !isAbsolute(fromRoot))) {
    return;
  }
  throw new Error(
    `Refusing to access path outside canonical ${options.scope} scope root ${options.scopeRoot}: ${normalized}`,
  );
}

async function verifyDirectoryChain(
  directory: string,
  options: ResolvedInstallOptions,
  operation: string,
): Promise<void> {
  const normalized = resolve(directory);
  assertConfined(normalized, options);
  const fromRoot = relative(options.scopeRoot, normalized);
  const segments = fromRoot === "" ? [] : fromRoot.split(sep);
  let current = options.scopeRoot;

  for (const segment of ["", ...segments]) {
    if (segment !== "") current = join(current, segment);
    try {
      const metadata = await lstat(current);
      if (metadata.isSymbolicLink()) {
        throw new Error(
          `Refusing to ${operation}: destination ancestor is a symbolic link: ${current}`,
        );
      }
      if (!metadata.isDirectory()) {
        throw new Error(
          `Refusing to ${operation}: destination ancestor is not a directory: ${current}`,
        );
      }
    } catch (error) {
      if (isMissingPathError(error)) return;
      throw error;
    }
  }
}

async function verifyDestination(
  path: string,
  options: ResolvedInstallOptions,
  operation: string,
): Promise<void> {
  assertConfined(path, options);
  await verifyDirectoryChain(dirname(path), options, operation);
}

async function resolveOptions(options: InstallOptions): Promise<ResolvedInstallOptions> {
  const scope = options.scope ?? "user";
  if (scope !== "user" && scope !== "project") {
    throw new Error(`Unsupported install scope: ${String(scope)}`);
  }
  let root = resolve(options.root ?? process.cwd());
  let home = resolve(options.home ?? homedir());
  const scopeInputRoot = scope === "user" ? home : root;
  const scopeRoot = await canonicalizeScopeRoot(scopeInputRoot);
  if (scope === "user") home = scopeRoot;
  else root = scopeRoot;
  const nodePath = resolve(options.nodePath ?? process.execPath);
  const cliPath = resolve(
    options.cliPath ?? join(DISTRIBUTION_DIRECTORY, "cli.js"),
  );
  return { scope, root, home, scopeRoot, scopeInputRoot, nodePath, cliPath };
}

function parseJsonObject(text: string, path: string): JsonObject {
  let value: unknown;
  try {
    value = JSON.parse(text) as unknown;
  } catch (error) {
    const detail = error instanceof Error ? error.message : String(error);
    throw new Error(`Refusing to modify ${path}: invalid JSON (${detail})`);
  }
  if (!isJsonObject(value)) {
    throw new Error(`Refusing to modify ${path}: expected a JSON object at the top level`);
  }
  return value;
}

async function readExistingJson(
  path: string,
  options: ResolvedInstallOptions,
): Promise<{ value: JsonObject; text: string | null; mode: number }> {
  try {
    await verifyDestination(path, options, "read configuration");
    const metadata = await lstat(path);
    if (!metadata.isFile()) {
      throw new Error(`Refusing to modify ${path}: path is not a regular file`);
    }
    await verifyDestination(path, options, "read configuration");
    const text = await readFile(path, "utf8");
    return { value: parseJsonObject(text, path), text, mode: metadata.mode & 0o777 };
  } catch (error) {
    if (isMissingPathError(error)) return { value: {}, text: null, mode: 0o600 };
    throw error;
  }
}

async function readJsonObjectConfined(
  path: string,
  options: ResolvedInstallOptions,
): Promise<JsonObject | null> {
  try {
    await verifyDestination(path, options, "inspect configuration");
    const metadata = await lstat(path);
    if (!metadata.isFile()) {
      throw new Error(`Cannot inspect ${path}: path is not a regular file`);
    }
    await verifyDestination(path, options, "inspect configuration");
    return parseJsonObject(await readFile(path, "utf8"), path);
  } catch (error) {
    if (isMissingPathError(error)) return null;
    throw error;
  }
}

async function atomicWriteJson(
  path: string,
  text: string,
  mode: number,
  options: ResolvedInstallOptions,
): Promise<void> {
  const parent = dirname(path);
  await verifyDirectoryChain(parent, options, "create configuration directory");
  await mkdir(parent, { recursive: true });
  await verifyDirectoryChain(parent, options, "write configuration");
  const temporary = `${path}.taskfence-tmp-${process.pid}-${Date.now()}`;
  let handle: FileHandle | undefined;
  try {
    await verifyDestination(temporary, options, "create temporary configuration");
    handle = await open(temporary, "wx", mode);
    await verifyDestination(temporary, options, "write temporary configuration");
    await handle.writeFile(text, "utf8");
    await handle.sync();
    await handle.close();
    handle = undefined;
    await verifyDestination(temporary, options, "rename temporary configuration");
    await verifyDestination(path, options, "replace configuration");
    await rename(temporary, path);
  } finally {
    await handle?.close().catch(() => undefined);
    try {
      await verifyDestination(temporary, options, "remove temporary configuration");
      await rm(temporary, { force: true });
    } catch (error) {
      if (!isMissingPathError(error)) throw error;
    }
  }
}

async function updateJsonObjectConfined(
  path: string,
  options: ResolvedInstallOptions,
  update: (value: JsonObject) => JsonObject,
): Promise<{ changed: boolean; backupPath?: string }> {
  const existing = await readExistingJson(path, options);
  const updated = update(structuredClone(existing.value));
  if (!isJsonObject(updated)) {
    throw new Error(`Refusing to modify ${path}: updater returned a non-object value`);
  }

  const before = JSON.stringify(existing.value);
  const after = JSON.stringify(updated);
  if (after === undefined) {
    throw new Error(`Refusing to modify ${path}: result is not JSON-serializable`);
  }
  if (before === after) return { changed: false };

  if (existing.text === null) {
    try {
      await verifyDestination(path, options, "check configuration");
      await lstat(path);
      throw new Error(`Refusing to modify ${path}: file appeared during update`);
    } catch (error) {
      if (!isMissingPathError(error)) throw error;
    }
  } else {
    await verifyDestination(path, options, "check configuration");
    if (await readFile(path, "utf8") !== existing.text) {
      throw new Error(`Refusing to modify ${path}: file changed during update`);
    }
  }

  let backupPath: string | undefined;
  if (existing.text !== null) {
    const timestamp = new Date().toISOString().replace(/[:.]/g, "-");
    backupPath = `${path}.taskfence-backup-${timestamp}-${process.pid}`;
    await verifyDestination(path, options, "read configuration backup source");
    await verifyDestination(backupPath, options, "write configuration backup");
    await copyFile(path, backupPath, fsConstants.COPYFILE_EXCL);
  }
  await atomicWriteJson(path, `${JSON.stringify(updated, null, 2)}\n`, existing.mode, options);
  return backupPath === undefined
    ? { changed: true }
    : { changed: true, backupPath };
}

function openCodeConfigDirectory(options: ResolvedInstallOptions): string {
  const configured = process.env.OPENCODE_CONFIG_DIR;
  if (configured === undefined) {
    return join(options.home, ".config", "opencode");
  }
  if (configured.length === 0 || configured.includes("\0") || !isAbsolute(configured)) {
    throw new Error("OPENCODE_CONFIG_DIR must contain a non-empty absolute path");
  }
  const configuredPath = resolve(configured);
  const fromInputRoot = relative(options.scopeInputRoot, configuredPath);
  if (
    fromInputRoot === "" ||
    (!fromInputRoot.startsWith(`..${sep}`) && fromInputRoot !== ".." && !isAbsolute(fromInputRoot))
  ) {
    return join(options.scopeRoot, fromInputRoot);
  }
  return configuredPath;
}

function configPath(runtime: InstallRuntime, options: ResolvedInstallOptions): string {
  const base = options.scope === "user" ? options.home : options.root;
  switch (runtime) {
    case "claude":
      return join(base, ".claude", "settings.json");
    case "codex":
      return join(base, ".codex", "hooks.json");
    case "opencode":
      return options.scope === "user"
        ? join(openCodeConfigDirectory(options), "plugins", "taskfence.ts")
        : join(options.root, ".opencode", "plugins", "taskfence.ts");
    case "omp":
      return options.scope === "user"
        ? join(options.home, ".omp", "agent", "extensions", "taskfence.js")
        : join(options.root, ".omp", "extensions", "taskfence.js");
    case "pi":
      return options.scope === "user"
        ? join(options.home, ".pi", "agent", "extensions", "taskfence.js")
        : join(options.root, ".pi", "extensions", "taskfence.js");
  }
}

function adapterPath(runtime: InstallRuntime): string {
  const filename = runtime === "claude"
    ? "claude-code.js"
    : runtime === "codex"
      ? "codex-cli.js"
      : `${runtime}.js`;
  return join(DISTRIBUTION_DIRECTORY, "adapters", filename);
}

function shellQuote(value: string): string {
  if (value.includes("\0")) throw new Error("Hook command paths cannot contain NUL bytes");
  return `'${value.replaceAll("'", `'"'"'`)}'`;
}

function hookHandler(runtime: "claude" | "codex", options: ResolvedInstallOptions): JsonObject {
  if (runtime === "claude") {
    return {
      type: "command",
      command: options.nodePath,
      args: [options.cliPath, "hook", "claude"],
      statusMessage: HOOK_STATUS,
    };
  }
  return {
    type: "command",
    command: `${shellQuote(options.nodePath)} ${shellQuote(options.cliPath)} hook codex`,
    statusMessage: HOOK_STATUS,
  };
}

function isOwnedHookHandler(
  value: unknown,
  expected: JsonObject,
): boolean {
  if (!isJsonObject(value)) return false;
  const expectedEntries = Object.entries(expected);
  if (Object.keys(value).length !== expectedEntries.length) return false;
  return expectedEntries.every(([key, expectedValue]) => {
    if (!Object.hasOwn(value, key)) return false;
    const actualValue = value[key];
    if (!Array.isArray(expectedValue)) return actualValue === expectedValue;
    return Array.isArray(actualValue) &&
      actualValue.length === expectedValue.length &&
      expectedValue.every((item, index) => actualValue[index] === item);
  });
}

function removeOwnedHandlers(
  config: JsonObject,
  expectedHandler: JsonObject,
): boolean {
  const hooksValue = config.hooks;
  if (hooksValue === undefined) return false;
  if (!isJsonObject(hooksValue)) {
    throw new Error("Refusing to modify hook config: hooks must be a JSON object");
  }

  let changed = false;
  for (const event of ["PreToolUse", "PostToolUse"] as const) {
    const groupsValue = hooksValue[event];
    if (groupsValue === undefined) continue;
    if (!Array.isArray(groupsValue)) {
      throw new Error(`Refusing to modify hook config: hooks.${event} must be an array`);
    }

    const keptGroups: unknown[] = [];
    for (const groupValue of groupsValue) {
      if (!isJsonObject(groupValue) || !Array.isArray(groupValue.hooks)) {
        keptGroups.push(groupValue);
        continue;
      }
      const ownsMatcher = groupValue.matcher === "*";
      const keptHandlers = groupValue.hooks.filter((handler) => {
        const owned = ownsMatcher && isOwnedHookHandler(handler, expectedHandler);
        if (owned) changed = true;
        return !owned;
      });
      if (keptHandlers.length > 0) {
        groupValue.hooks = keptHandlers;
        keptGroups.push(groupValue);
      } else if (
        groupValue.hooks.length === 0 ||
        Object.keys(groupValue).some((key) => key !== "matcher" && key !== "hooks")
      ) {
        groupValue.hooks = [];
        keptGroups.push(groupValue);
      }
    }
    if (keptGroups.length > 0) hooksValue[event] = keptGroups;
    else delete hooksValue[event];
  }
  if (Object.keys(hooksValue).length === 0) delete config.hooks;
  return changed;
}

function addHookGroups(
  config: JsonObject,
  runtime: "claude" | "codex",
  options: ResolvedInstallOptions,
): JsonObject {
  const expectedHandler = hookHandler(runtime, options);
  removeOwnedHandlers(config, expectedHandler);
  if (config.hooks === undefined) config.hooks = {};
  if (!isJsonObject(config.hooks)) {
    throw new Error("Refusing to modify hook config: hooks must be a JSON object");
  }
  for (const event of ["PreToolUse", "PostToolUse"] as const) {
    if (config.hooks[event] === undefined) config.hooks[event] = [];
    const groups = config.hooks[event];
    if (!Array.isArray(groups)) {
      throw new Error(`Refusing to modify hook config: hooks.${event} must be an array`);
    }
    groups.push({ matcher: "*", hooks: [hookHandler(runtime, options)] });
  }
  return config;
}

async function rejectCodexInlineHooks(options: ResolvedInstallOptions): Promise<void> {
  const base = options.scope === "user" ? options.home : options.root;
  const tomlPath = join(base, ".codex", "config.toml");
  try {
    await verifyDestination(tomlPath, options, "read Codex configuration");
    const metadata = await lstat(tomlPath);
    if (!metadata.isFile()) {
      throw new Error(`Refusing to read ${tomlPath}: path is not a regular file`);
    }
    await verifyDestination(tomlPath, options, "read Codex configuration");
    const toml = await readFile(tomlPath, "utf8");
    if (/^\s*\[\[?hooks(?:\.|\])/m.test(toml)) {
      throw new Error(
        `Refusing to create ${configPath("codex", options)}: ${tomlPath} already defines inline hooks`,
      );
    }
  } catch (error) {
    if (isMissingPathError(error)) return;
    throw error;
  }
}

async function installJsonHooks(
  runtime: "claude" | "codex",
  options: ResolvedInstallOptions,
): Promise<InstallReport> {
  if (runtime === "codex") await rejectCodexInlineHooks(options);
  const path = configPath(runtime, options);
  const existed = await readJsonObjectConfined(path, options) !== null;
  const result = await updateJsonObjectConfined(
    path,
    options,
    (config) => addHookGroups(config, runtime, options),
  );
  return {
    runtime,
    scope: options.scope,
    path,
    action: result.changed ? (existed ? "updated" : "installed") : "unchanged",
    ...(result.backupPath === undefined ? {} : { backupPath: result.backupPath }),
  };
}

async function uninstallJsonHooks(
  runtime: "claude" | "codex",
  options: ResolvedInstallOptions,
): Promise<InstallReport> {
  const path = configPath(runtime, options);
  const existing = await readJsonObjectConfined(path, options);
  if (existing === null) {
    return { runtime, scope: options.scope, path, action: "not-installed" };
  }
  const expectedHandler = hookHandler(runtime, options);
  const result = await updateJsonObjectConfined(path, options, (config) => {
    removeOwnedHandlers(config, expectedHandler);
    return config;
  });
  return {
    runtime,
    scope: options.scope,
    path,
    action: result.changed ? "removed" : "not-installed",
    ...(result.backupPath === undefined ? {} : { backupPath: result.backupPath }),
  };
}

function loaderSource(): string {
  const specifier = pathToFileURL(adapterPath("opencode")).href;
  return `${LOADER_MARKER}\nimport TaskFencePlugin from ${JSON.stringify(specifier)};\n\nexport default TaskFencePlugin;\n`;
}

async function timestampedBackup(
  path: string,
  options: ResolvedInstallOptions,
): Promise<string> {
  const timestamp = new Date().toISOString().replace(/[:.]/g, "-");
  const backupPath = `${path}.taskfence-backup-${timestamp}-${process.pid}`;
  await verifyDestination(path, options, "read backup source");
  await verifyDestination(backupPath, options, "write backup");
  await copyFile(path, backupPath, fsConstants.COPYFILE_EXCL);
  return backupPath;
}

async function installLoader(options: ResolvedInstallOptions): Promise<InstallReport> {
  const runtime = "opencode" as const;
  const path = configPath(runtime, options);
  const desired = loaderSource();
  let existing: string | null = null;
  try {
    await verifyDestination(path, options, "inspect OpenCode loader");
    const metadata = await lstat(path);
    if (!metadata.isFile()) {
      throw new Error(`Refusing to replace ${path}: path is not a regular file`);
    }
    await verifyDestination(path, options, "read OpenCode loader");
    existing = await readFile(path, "utf8");
  } catch (error) {
    if (!isMissingPathError(error)) throw error;
  }
  if (existing === desired) {
    return { runtime, scope: options.scope, path, action: "unchanged" };
  }
  if (existing !== null && !existing.startsWith(`${LOADER_MARKER}\n`)) {
    throw new Error(`Refusing to replace unrelated OpenCode plugin: ${path}`);
  }

  const parent = dirname(path);
  await verifyDirectoryChain(parent, options, "create OpenCode plugin directory");
  await mkdir(parent, { recursive: true });
  await verifyDirectoryChain(parent, options, "write OpenCode loader");
  let backupPath: string | undefined;
  if (existing !== null) backupPath = await timestampedBackup(path, options);
  const temporary = `${path}.taskfence-tmp-${process.pid}-${Date.now()}`;
  try {
    await verifyDestination(temporary, options, "write temporary OpenCode loader");
    await writeFile(temporary, desired, { encoding: "utf8", flag: "wx", mode: 0o644 });
    await verifyDestination(temporary, options, "rename temporary OpenCode loader");
    await verifyDestination(path, options, "replace OpenCode loader");
    await rename(temporary, path);
  } finally {
    try {
      await verifyDestination(temporary, options, "remove temporary OpenCode loader");
      await rm(temporary, { force: true });
    } catch (error) {
      if (!isMissingPathError(error)) throw error;
    }
  }
  return {
    runtime,
    scope: options.scope,
    path,
    action: existing === null ? "installed" : "updated",
    ...(backupPath === undefined ? {} : { backupPath }),
  };
}

async function uninstallLoader(options: ResolvedInstallOptions): Promise<InstallReport> {
  const runtime = "opencode" as const;
  const path = configPath(runtime, options);
  try {
    await verifyDestination(path, options, "inspect OpenCode loader for uninstall");
    const metadata = await lstat(path);
    if (!metadata.isFile()) {
      throw new Error(`Refusing to remove ${path}: path is not a regular file`);
    }
    await verifyDestination(path, options, "read OpenCode loader for uninstall");
    const existing = await readFile(path, "utf8");
    if (!existing.startsWith(`${LOADER_MARKER}\n`)) {
      throw new Error(`Refusing to remove unrelated OpenCode plugin: ${path}`);
    }
    await verifyDestination(path, options, "remove OpenCode loader");
    await rm(path);
    return { runtime, scope: options.scope, path, action: "removed" };
  } catch (error) {
    if (isMissingPathError(error)) {
      return { runtime, scope: options.scope, path, action: "not-installed" };
    }
    throw error;
  }
}

async function installExtension(
  runtime: "omp" | "pi",
  options: ResolvedInstallOptions,
): Promise<InstallReport> {
  const path = configPath(runtime, options);
  const target = adapterPath(runtime);
  try {
    await verifyDestination(path, options, `inspect ${runtime} extension`);
    const metadata = await lstat(path);
    if (!metadata.isSymbolicLink()) {
      throw new Error(`Refusing to replace unrelated extension: ${path}`);
    }
    await verifyDestination(path, options, `read ${runtime} extension symlink`);
    const currentTarget = resolve(dirname(path), await readlink(path));
    if (currentTarget === target) {
      return { runtime, scope: options.scope, path, action: "unchanged" };
    }
    throw new Error(`Refusing to replace symlink not owned by this TaskFence install: ${path}`);
  } catch (error) {
    if (!isMissingPathError(error)) throw error;
  }
  const parent = dirname(path);
  await verifyDirectoryChain(parent, options, `create ${runtime} extension directory`);
  await mkdir(parent, { recursive: true });
  await verifyDirectoryChain(parent, options, `create ${runtime} extension symlink`);
  await verifyDestination(path, options, `create ${runtime} extension symlink`);
  await symlink(target, path);
  return { runtime, scope: options.scope, path, action: "installed" };
}

async function uninstallExtension(
  runtime: "omp" | "pi",
  options: ResolvedInstallOptions,
): Promise<InstallReport> {
  const path = configPath(runtime, options);
  const target = adapterPath(runtime);
  try {
    await verifyDestination(path, options, `inspect ${runtime} extension for uninstall`);
    const metadata = await lstat(path);
    if (!metadata.isSymbolicLink()) {
      throw new Error(`Refusing to remove unrelated extension: ${path}`);
    }
    await verifyDestination(path, options, `read ${runtime} extension symlink for uninstall`);
    if (resolve(dirname(path), await readlink(path)) !== target) {
      throw new Error(`Refusing to remove symlink not owned by this TaskFence install: ${path}`);
    }
    await verifyDestination(path, options, `remove ${runtime} extension`);
    await rm(path);
    return { runtime, scope: options.scope, path, action: "removed" };
  } catch (error) {
    if (isMissingPathError(error)) {
      return { runtime, scope: options.scope, path, action: "not-installed" };
    }
    throw error;
  }
}

export async function installRuntime(
  runtime: InstallRuntime,
  options: InstallOptions = {},
): Promise<InstallReport> {
  const resolved = await resolveOptions(options);
  if (runtime === "claude" || runtime === "codex") {
    return installJsonHooks(runtime, resolved);
  }
  if (runtime === "opencode") return installLoader(resolved);
  return installExtension(runtime, resolved);
}

export async function uninstallRuntime(
  runtime: InstallRuntime,
  options: InstallOptions = {},
): Promise<InstallReport> {
  const resolved = await resolveOptions(options);
  if (runtime === "claude" || runtime === "codex") {
    return uninstallJsonHooks(runtime, resolved);
  }
  if (runtime === "opencode") return uninstallLoader(resolved);
  return uninstallExtension(runtime, resolved);
}

export async function isRuntimeConfigured(
  runtime: InstallRuntime,
  options: InstallOptions = {},
): Promise<{ configured: boolean; path: string; detail: string }> {
  const resolved = await resolveOptions(options);
  const path = configPath(runtime, resolved);
  try {
    if (runtime === "claude" || runtime === "codex") {
      const config = await readJsonObjectConfined(path, resolved);
      if (config === null || !isJsonObject(config.hooks)) {
        return { configured: false, path, detail: "TaskFence hook groups not found" };
      }
      const expected = hookHandler(runtime, resolved);
      for (const event of ["PreToolUse", "PostToolUse"] as const) {
        const groups = config.hooks[event];
        if (!Array.isArray(groups) || !groups.some((group) =>
          isJsonObject(group) && group.matcher === "*" && Array.isArray(group.hooks) &&
          group.hooks.some((handler) => isOwnedHookHandler(handler, expected))
        )) {
          return { configured: false, path, detail: `TaskFence ${event} hook not found` };
        }
      }
      return { configured: true, path, detail: "PreToolUse and PostToolUse hooks configured" };
    }
    if (runtime === "opencode") {
      await verifyDestination(path, resolved, "inspect OpenCode loader");
      const metadata = await lstat(path);
      if (!metadata.isFile()) {
        throw new Error(`Cannot inspect ${path}: path is not a regular file`);
      }
      await verifyDestination(path, resolved, "read OpenCode loader");
      const content = await readFile(path, "utf8");
      const configured = content === loaderSource();
      return {
        configured,
        path,
        detail: configured ? "TaskFence loader configured" : "Loader differs from this TaskFence install",
      };
    }
    await verifyDestination(path, resolved, `inspect ${runtime} extension`);
    const metadata = await lstat(path);
    let configured = false;
    if (metadata.isSymbolicLink()) {
      await verifyDestination(path, resolved, `read ${runtime} extension symlink`);
      configured = resolve(dirname(path), await readlink(path)) === adapterPath(runtime);
    }
    return {
      configured,
      path,
      detail: configured ? "TaskFence extension symlink configured" : "Extension path is not this TaskFence adapter",
    };
  } catch (error) {
    if (isMissingPathError(error)) {
      return { configured: false, path, detail: "Installation entry not found" };
    }
    const detail = error instanceof Error ? error.message : "Unable to inspect installation";
    return { configured: false, path, detail };
  }
}
